
mode: standalone

environment:
  MINIO_PROMETHEUS_URL: "http://prometheus-server.observability.svc.cluster.local/"

persistence:
  size: 20Gi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /minio/v2/metrics/cluster
  prometheus.io/port: "9000"

resources:
  requests:
    memory: 1Gi
