
datasources:
  default.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki:3100
      version: 1
      isDefault: true
      jsonData:
        manageAlerts: true
        maxLines: 5000
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
    - name: prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://prometheus-server
      version: 1
      isDefault: false
      timeInterval: '10s'
      jsonData:
        manageAlerts: true
        exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
    - name: tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://tempo:3100
      version: 1
      isDefault: false
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['job', 'instance', 'pod', 'namespace']
          # mappedTags: [{ key: 'service.name', value: 'service' }]
          mapTagNamesEnabled: true
          spanStartTimeShift: '-30s'
          spanEndTimeShift: '30s'
          filterByTraceID: false
          filterBySpanID: false
        serviceMap:
          datasourceUid: 'prometheus'
        search:
          hide: false
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: loki
service:
  port: 3000
  # type: NodePort
  # nodePort: 3000
persistence:
  enabled: true
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "3000"
