# podAnnotations:
#   prometheus.io/scrape: "true"
#   prometheus.io/path: /metrics
#   prometheus.io/port: "3100"
persistence:
  enabled: true

monitoring:
  dashboards:
    enabled: true
    namespace: observability
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
write:
  affinity: |
    podAntiAffinity:
read:
  affinity: |
    podAntiAffinity:

test:
  enabled: false
minio:
  enabled: true
