podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "3101"
config:
  clients:
    - url: "http://loki-write:3100/loki/api/v1/push"
      tenant_id: default
